version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/workflowmanagement
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_EXPIRE=24h
      - CLIENT_URL=http://localhost:5173
      # Gmail settings, replace these with your actual values or use .env file
      - USE_GMAIL=${USE_GMAIL}
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - app-network
    environment:
      # These settings are for development only, add authentication for production
      - MONGO_INITDB_DATABASE=workflowmanagement

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: 