version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/workflowmanagement
      - JWT_SECRET=dev_jwt_secret
      - JWT_EXPIRE=24h
      - CLIENT_URL=http://localhost:5173
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    command: npm run dev
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_dev:/data/db
    networks:
      - app-network
    environment:
      - MONGO_INITDB_DATABASE=workflowmanagement

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data_dev: 